app/blueprints/instructor/__init__.py
from tkinter.font import names
from flask import (
    Blueprint,
    render_template,
    current_app,
    url_for,
    session,
    redirect,
    abort,
    g,
)
from app.filePath_provider import listOfdashboardComponentsPaths, imagesUrl
from app.authorizer import authorize_with
from ..uploads import uploads

instructor = Blueprint("instructor", __name__, template_folder="templates")
instructor.register_blueprint(uploads, url_prefix="/uploads")


@instructor.route("/dashboard")
def dashboard():
    return render_template(
        "instructor/dashboard.html",
        components=listOfdashboardComponentsPaths(instructor),
    )


@instructor.before_request
@authorize_with([], True, ["instructor", "admin"])
def middleware():
    pass


@instructor.route("/courseList")
def courseList():
    return render_template(
        "instructor/courseList.html",
        imagesUrl=imagesUrl(),
    )

@instructor.route("/images")
def images():
    from flask import jsonify
    return jsonify(imagesUrl())
    



@instructor.route("/versionTree/", defaults={"courseCode": None})
@instructor.route("/versionTree/<courseCode>")
def versionTree(courseCode):
    if courseCode is not None:
        return render_template(
            "collegue/versionTree.html",
            courseCode=courseCode,
        )
    abort(404)


@instructor.route("/coursePlan/", defaults={"courseCode": None})
@instructor.route("/coursePlan/<courseCode>")
def coursePlan(courseCode):
    if courseCode is not None:
        return render_template(
            "shared/coursePlan/coursePlan.html", courseCode=courseCode
        )
    abort(404)


@instructor.route("/material/", defaults={"courseCode": None})
@instructor.route("/material/<courseCode>")
def material(courseCode):
    if courseCode is not None:
        return render_template("instructor/material.html", courseCode=courseCode)
    abort(404)


@instructor.route("/schedule")
def schedule():
    return "not implemented"


@instructor.route("/workspace/", defaults={"deltaGraphId": None})
@instructor.route("/workspace/<deltaGraphId>")
def workspace(deltaGraphId):
    if deltaGraphId is not None:
        return render_template("instructor/graphEditor.html", deltaGraphId=deltaGraphId)
    abort(404)


@instructor.route(
    "/workspace/commit/", defaults={"overwriterId": None, "overwriteeId": None}
)
@instructor.route("/workspace/commit/<overwriterId>/", defaults={"overwriteeId": None})
@instructor.route("/workspace/commit/<overwriterId>/<overwriteeId>")
def commit(overwriterId, overwriteeId):
    if overwriterId is not None:
        return render_template(
            "collegue/graphCompare.html",
            overwriterId=overwriterId,
            overwriteeId=overwriteeId,
        )
    abort(404)


@instructor.route("/branch/", defaults={"overwriterId": None, "overwriteeId": None})
@instructor.route("/branch/<overwriterId>/", defaults={"overwriteeId": None})
@instructor.route("/branch/<overwriterId>/<overwriteeId>")
def branch(overwriterId, overwriteeId):
    if overwriterId is not None:
        return render_template(
            "collegue/graphCompare.html",
            overwriterId=overwriterId,
            overwriteeId=overwriteeId,
        )
    abort(404)


@instructor.route("/import/", defaults={"deltaGraphId": None})
@instructor.route("/import/<deltaGraphId>/")
def graphImport(deltaGraphId):
    if deltaGraphId is not None:
        return render_template("instructor/graphImport.html", deltaGraphId=deltaGraphId)
    abort(404)


@instructor.route("/courseCreate")
def courseForm():
    return render_template(
        "instructor/courseForm.html",
        imagesUrl=imagesUrl(),
    )


@instructor.route("/upload")
def uploadImage():
    return render_template("instructor/uploadImage.html")


@instructor.route("/repositories/", defaults={"courseCode": None})
@instructor.route("/repositories/<courseCode>")
def repositories(courseCode):
    return render_template("instructor/repository.html", courseCode=courseCode)


@instructor.route("/repositories/<courseCode>/versions/", defaults={"id": None})
@instructor.route("/repositories/<courseCode>/versions/<id>")
def repositoryVersions(courseCode, id):
    return render_template(
        "instructor/repositoryVersions.html", courseCode=courseCode, id=id
    )



@instructor.route("/entityEditor", defaults={"courseCode": None, "name": None})
@instructor.route("/entityEditor/<courseCode>/", defaults={"name": None})
@instructor.route("/entityEditor/<courseCode>/<path:name>")
def entityEditor(courseCode, name):
    from app.api_driver import get_api_driver

    return render_template(
        "instructor/entityEditor.html",
        courseCode=courseCode,
        name=name,
    )

app/blueprints/instructor/templates/instructor/component/summary.html
{% macro componentContent() %}
<div style="height: 100%; width: 100%;">
    summary
</div>
{% endmacro %}
{% macro component() %}
<script type="text/x-template" id="kcube-instructor-summary">
    {{ componentContent()}}
</script>
{% endmacro %}
{% macro script() %}
<script src="https://unpkg.com/vue-iro-color-picker@2.0.0/dist/VueIroColorPicker.umd.min.js"></script>
<script>
    widgetName = 'summary'
    widgetComponentName = 'kcube-instructor-summary'
    KCube.widgetName.push(widgetName)
    KCube.widgetOptions[widgetName] = {
        component: widgetComponentName
    }
    Vue.component(widgetComponentName, {
        data: () => ({
        }),
        methods: {
        },
        template: '#' + widgetComponentName,
        delimiters: ['${', '}'],
    })
</script>
{% endmacro %}
{{ component() }}
{{ script() }}

app/blueprints/instructor/templates/instructor/coursePreview.html
{% macro componentContent() %}
<v-card>
    <v-container>
        <v-row>
            <v-card-title>
                ${courseCode}
            </v-card-title>
        </v-row>
        <v-row>
            <v-card-title>
                Public graph provided by:
            </v-card-title>
        </v-row>
        <v-row v-for="row in rows">
            <v-col v-for="col in row" cols="3" class="d-flex" style="flex-direction:column">
                <v-card v-if="col.userName" :href="'{{ url_for('courseGraph') }}' + courseCode + (col.userId !=
            null ? '/' + col.userId : '')">
                    <v-list-item>
                        <v-list-item-title>
                            ${col.userName}
                        </v-list-item-title>
                    </v-list-item>
                </v-card>
            </v-col>
        </v-row>
        {% if session['user'] and session['user']['userId'] %}
        <v-row>
            <v-col cols="auto">
                <v-card-subtitle>
                    Last-visited workspace:
                </v-card-subtitle>
            </v-col>
            <v-col cols="auto">
                <v-btn v-if="lastModifiedWorkspace===undefined">
                    <v-progress-circular indeterminate></v-progress-circular>
                </v-btn>
                <v-btn v-else-if="lastModifiedWorkspace" style="height: 48px;"
                    :href="'{{ url_for('instructor.workspace')}}' + lastModifiedWorkspace.deltaGraphId">
                    <v-icon>work</v-icon>
                </v-btn>
                <v-btn v-else @click="openWorkspaceDialogue()">create workspace</v-btn>
            </v-col>
            <v-col v-if="lastModifiedWorkspace">
                <v-card-subtitle>
                    workspace tag: ${lastModifiedWorkspace.tag}
                </v-card-subtitle>
            </v-col>
        </v-row>
        {% endif %}
        <v-dialog v-model="workspaceDialogue" max-width="500px">
            <kcube-workspace-form ref="workspaceForm"></kcube-workspace-form>
        </v-dialog>
    </v-container>
</v-card>
{% endmacro %}
{% macro component() %}
<script type="text/x-template" id="kcube-course-preview">
    {{ componentContent()}}
</script>
{% endmacro %}
{% macro script() %}
<script>
    Vue.component('kcube-course-preview', {
        data: () => ({
            rows: [
                []
            ],
            courseCode: null,
            //{% if PERMISSION and PERMISSION.role and ("admin" in PERMISSION.role or "instructor" in PERMISSION.role) %}
            lastModifiedWorkspace: undefined,
            //{% endif %}
            workspaceDialogue: false
        }),
        methods: {
            loadData(courseCode) {
                this.courseCode = courseCode
                this.$root.progress.show = true
                this.lastModifiedWorkspace = undefined
                fetch(
                    "{{ url_for('RESTful.course.query', graphs=True) | safe }}&courseCode=" + this.courseCode, {
                    method: 'GET',
                    cache: 'no-store',
                    headers: {
                        'Content-Type': 'application/json'
                    }
                })
                    .then(response => {
                        try {
                            return response.json()
                        } catch {
                            this.$root.progress.show = false
                            this.$root.errorDisplay({},
                                'Unexpected error occured.')
                        }
                    })
                    .then(body => {
                        this.rows = [
                            []
                        ]
                        this.$root.progress.show = false
                        let colPerRow = 4
                        if (body.instructors) {
                            body.instructors.forEach(instructor => {
                                let lastRow = this.rows[this.rows.length - 1]
                                if (lastRow.length == colPerRow) {
                                    this.rows.push([])
                                    lastRow = this.rows[this.rows.length - 1]
                                }
                                lastRow.push(instructor)

                            })
                            let lastRow = this.rows[this.rows.length - 1]
                            if (lastRow.length == colPerRow) {
                                this.rows.push([])
                                lastRow = this.rows[this.rows.length - 1]
                            }
                            lastRow.push({
                                userName: 'department',
                                userId: null
                            })
                            while (lastRow.length < colPerRow) {
                                lastRow.push({})
                            }
                        } else {
                            this.$root.errorDisplay(body,
                                'Unexpected error on getting courses information.')
                        }
                    })
                //{% if PERMISSION and PERMISSION.role and ("admin" in PERMISSION.role or "instructor" in PERMISSION.role) %}
                fetch(
                    "{{ url_for('RESTful.workspace.query', lastModified=True) | safe }}&courseCode=" + this.courseCode, {
                    method: 'GET',
                    cache: 'no-store',
                    headers: {
                        'Content-Type': 'application/json'
                    }
                })
                    .then(response => {
                        try {
                            return response.json()
                        } catch {
                            this.$root.progress.show = false
                            this.$root.errorDisplay({},
                                'Unexpected error occured.')
                        }
                    })
                    .then(body => {
                        this.$root.progress.show = false
                        let colPerRow = 4
                        if (body.workspaces) {
                            if (body.workspaces.length > 0) {
                                this.lastModifiedWorkspace = body.workspaces[0]
                            }
                            else {
                                this.lastModifiedWorkspace = null
                            }
                        } else {
                            this.$root.errorDisplay(body,
                                'Unexpected error on getting workspace information.')
                        }
                    })
                //{% endif %}
            },
            openWorkspaceDialogue() {
                this.$refs.workspaceForm.loadData(this.courseCode);
                this.workspaceDialogue = true;
            }
        },
        template: '#kcube-course-preview',
        delimiters: ['${', '}'],
    })
</script>
{% endmacro %}
{% include "instructor/workspaceForm.html" %}
{{ component() }}
{{ script() }}

app/blueprints/instructor/templates/instructor/dashboard.html
{% extends "shared/dashboard.html" %}
{% block widget %}
{% for file_name in components%}
    {% include file_name %}
{% endfor %}
{% endblock %}

app/blueprints/instructor/templates/instructor/repositoryVersions.html
{% extends "layout.html" %}
{% import 'layout.html' as layout with context %}
{% block VueComponent %}
<v-card>
    <v-container>
        <v-row>
            <v-text-field v-model="search" append-icon="mdi-magnify" label="Search" hide-details>
            </v-text-field>
        </v-row>
        <v-row>
            <v-data-table show-group-by :headers="headers" style="width:100%" :items="versions" :items-per-page="500"
                multi-sort :search="search">
                <template v-slot:item.actions="{ item }">
                    <v-row>
                        <v-col cols="auto">
                            <v-tooltip bottom>
                                <template v-slot:activator="{ on, attrs }">
                                    <v-btn icon v-bind="attrs" v-on="on"
                                        :href="'{{ url_for('collegue.compare')}}' + item.deltaGraphId + '/' + item.parent.property.deltaGraphId">
                                        <v-icon>
                                            preview
                                        </v-icon>
                                    </v-btn>
                                </template>
                                view changes
                            </v-tooltip>
                            <v-tooltip bottom>
                                <template v-slot:activator="{ on, attrs }">
                                    <v-btn icon v-bind="attrs" v-on="on"
                                        :href="'{{ url_for('instructor.graphImport')}}' + item.deltaGraphId">
                                        <v-icon>
                                            data_object
                                        </v-icon>
                                    </v-btn>
                                </template>
                                json import
                            </v-tooltip>
                        </v-col>
                        <v-col>
                            <v-tooltip bottom>
                                <template v-slot:activator="{ on, attrs }">
                                    <span>
                                        <v-btn icon v-bind="attrs" v-on="on" v-if="item.workspaces?.length==1"
                                            :href="'{{ url_for('instructor.workspace')}}' + item.workspaces[0].deltaGraphId">
                                            <v-icon>
                                                work
                                            </v-icon>
                                        </v-btn>
                                        <v-autocomplete dense append-outer-icon="work" v-bind="attrs" v-on="on"
                                            item-text="tag" item-value="deltaGraphId" v-if="item.workspaces?.length>1"
                                            :items="item.workspaces"
                                            @change="this.window.open('{{ url_for('instructor.workspace')}}' + $event, '_blank')">
                                            <template v-slot:item="data">
                                                <v-list-item-content>
                                                    ${data.item.tag!=''?data.item.tag:'(unnamed)'}
                                                </v-list-item-content>
                                            </template>
                                        </v-autocomplete>
                                        <v-btn icon v-bind="attrs" v-on="on" v-if="item.workspaces.length == 0"
                                            @click="createWorkspaceDialogue(item.deltaGraphId)">
                                            <v-icon>
                                                work_outline
                                            </v-icon>
                                        </v-btn>
                                    </span>
                                </template>
                                ${item.workspaces?'workspace' + (item.workspaces.length==1?'':'s') +' for latest'+
                                ' version':'create workspace for latest version'}
                            </v-tooltip>
                        </v-col>
                    </v-row>
                </template>
                <template v-slot:item.creationDate="{ item }">
                    ${item.creationDate | formatDate}
                </template>

                <template v-slot:item.pullRequest="{ item }">
                    <v-simple-checkbox :value="item.pullRequest" readonly color="info"
                        @click="readyToPush(item.deltaGraphId,!item.pullRequest)"></v-simple-checkbox>
                </template>
            </v-data-table>
        </v-row>
    </v-container>
    <v-dialog v-model="workspaceCreateDialog">
        <v-card>
            <v-card-title class="text-h5 grey lighten-2">
                Give a name tag to your new workspace:
            </v-card-title>
            <v-form ref="createWorkspaceControl">
                <v-text-field label="tag" :rules="tagRules" v-model="tag" required></v-text-field>
            </v-form>
            <v-divider></v-divider>

            <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn color="primary" text @click="createWorkspace()">
                    create
                </v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>
</v-card>
{% endblock %}
{% block VueComponentScript %}
<script>
    Vue.filter("formatDate", (value) => {
        if (value) {
            return (new Date(value)).toLocaleString("en-US", {})
        }
    })
    Vue.component('app-content', {
        data: () => ({
            search: new URLSearchParams(window.location
                .search).get('concept'),
            versions: [],
            headers: [{
                    text: 'tag',
                    value: 'tag',
                    groupable: false,
                },
                {
                    text: 'creation date',
                    value: 'creationDate',
                    groupable: false,
                },
                {
                    text: '',
                    value: 'info',
                    groupable: false,
                },
                {
                    text: 'pull request made',
                    value: 'pullRequest'
                },
                {
                    text: '',
                    value: 'actions',
                    groupable: false,
                },
            ],
            workspaceCreateDialog: false,
            tag: '',
            tagRules: [v => !!v || 'Tag name is required',
                v => (v && v.length > 3 && v.length < 101) ||
                'Tag name should be anything between 4 and 100 charactors',
                v => (v && /{{regExpRules["tag"]}}/.test(v)) ||
                'Tag name can only contains alphanumeric characters, hyphen, comma, colon, dot and space.'
            ],
        }),
        methods: {
            loadData() {
                this.$root.progress.show = true
                let treePromise =
                    fetch(
                        "{{ url_for('RESTful.tree.get', courseCode = courseCode, isInstructor = True, isDLTC = False) }}", {
                            method: 'GET',
                            cache: 'no-store',
                            headers: {
                                'Content-Type': 'application/json'
                            }
                        })
                    .then(response => {
                        try {
                            return response.json()
                        } catch {
                            this.$root.progress.show = false
                            this.$root.errorDisplay({},
                                'Unexpected error occured.')
                        }
                    })
                    .then(body => {
                        this.versions = []
                        if (body.edges && body.trunk_nodes && body.branch_nodes && body.workspace_nodes) {
                            let candidate = body.edges.filter(e => e.start ==
                                "{{ id }}")
                            do {
                                let cursor = candidate[0].start
                                let branch = body.branch_nodes.filter(b => b.id == cursor)[0]
                                let parent = body.branch_nodes.filter(b => b.id == candidate[0].end)[0]
                                parent = parent ? parent : body.trunk_nodes.filter(b => b.id == candidate[0]
                                    .end)[0]
                                let work_on_candidate = body.edges.filter(e => e.type ==
                                    "WORK_ON" && e.end == cursor)
                                let workspaces = work_on_candidate.map(we => {
                                    return body.workspace_nodes
                                        .filter(w => w.id == we.start)[0].property
                                }).sort(function (a, b) {
                                    return new Date(b.lastModified) - new Date(a.lastModified);
                                })
                                this.versions.push({
                                    tag: branch.property.tag,
                                    creationDate: branch.property.creationDate,
                                    owned: branch.isOwner,
                                    exposed: branch.isExposed,
                                    deltaGraphId: branch.property.deltaGraphId,
                                    parent: parent,
                                    workspaces: workspaces,
                                    pullRequest: branch.property.canPull ? true : false
                                })
                                candidate = body.edges.filter(e => e.type == "PATCH" && e.end &&
                                    e.end == cursor)
                            }
                            while (candidate.length > 0)

                        } else {
                            this.$root.errorDisplay(body,
                                'Unexpected error on getting versions information.')
                        }
                    })
                Promise.all([treePromise]).then(_ => {
                    this.$root.progress.show = false
                })
            },
            newTab(id) {
                let w = window.open("{{ url_for('instructor.repositoryVersions', courseCode=courseCode) }}/" +
                    id, '_blank')
            },
            readyToPush(id, value) {
                if (this.$root.progress.show == true) {
                    this.$root.bePatientSnackBar.show = true
                    return
                }
                this.$root.progress.show = true
                fetch("{{ url_for('RESTful.branch.patch') }}" + id, {
                        method: 'PATCH',
                        cache: 'no-store',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            canPull: value
                        })
                    })
                    .then(response => {
                        return response.json()
                    })
                    .then(body => {
                        this.$root.progress.show = false
                        this.$root.responseSnackBar(body,
                            'Creation failed for unknown reason.',
                            () => {
                                this.loadData()
                            })
                    })
            },
            createWorkspaceDialogue(deltaGraphId) {
                this.workspaceCreateDialog = true
                this.deltaGraphId = deltaGraphId
            },
            createWorkspace() {
                if (this.$refs.createWorkspaceControl.validate()) {
                    if (this.$root.progress.show == true) {
                        this.$root.bePatientSnackBar.show = true
                        return
                    }
                    this.$root.progress.show = true
                    fetch("{{ url_for('RESTful.workspace.post') }}" + this.deltaGraphId, {
                            method: 'POST',
                            cache: 'no-store',
                            headers: {
                                'Content-Type': 'application/json'
                            },
                            body: JSON.stringify({
                                tag: this.tag,
                            })
                        })
                        .then(response => {
                            return response.json()
                        })
                        .then(body => {
                            this.$root.progress.show = false
                            this.$root.responseSnackBar(body,
                                'Creation failed for unknown reason.',
                                () => {
                                    this.workspaceCreateDialog = false
                                    this.$refs.createWorkspaceControl.reset()
                                    this.loadData()
                                })
                        })
                }
            },
        },
        mounted: function () {
            this.loadData()
        },
        template: '#content',
        delimiters: ['${', '}'],
    })
</script>
{% endblock %}

app/blueprints/instructor/templates/instructor/uploadImage.html
{% extends "layout.html" %}
{% import 'layout.html' as layout with context %}
{% block VueComponent %}
<v-form ref="imageForm">
    <v-container>
        <v-row>
            <v-col>
                <v-file-input accept="image/*" name="file" label="File input" multiple required></v-file-input>
            </v-col>
            <v-col>
                <v-btn @click="uploadImage" color="success">Upload</v-btn>
            </v-col>
        </v-row>
    </v-container>
</v-form>
{% endblock %}
{% block VueComponentScript %}
<script>
    Vue.component('app-content', {
        data: () => ({

        }),
        methods: {
            uploadImage() {
                if (this.$refs.imageForm.validate()) {
                    if (this.$root.progress.show == true) {
                        this.$root.bePatientSnackBar.show = true
                        return
                    }
                    let formData = new FormData(this.$refs.imageForm.$el)
                    this.$root.progress.show = true
                    fetch("{{ url_for(request.blueprint+'.uploads.image') }}", {
                            method: 'POST',
                            cache: 'no-store',
                            body: formData
                        })
                        .then(response => {
                            try {
                                return response.json()
                            } catch {
                                this.$root.progress.show = false
                                this.$root.errorDisplay({},
                                    'Unexpected error occured.')
                            }
                        })
                        .then(body => {
                            this.$root.progress.show = false;
                            (new BroadcastChannel("*-courseForm"))
                            .postMessage({
                                message: 'imageUploaded',
                                payload: body.urls
                            }, '*')
                            this.$root.responseSnackBar(body,
                                'unexpected error',
                                this.$refs.imageForm.reset)

                        })
                }
            }
        },
        template: '#content'
    })
</script>
{% endblock %}